name: massa

repository: https://github.com/jwmdev/massa-dart

packages:
  - /**

scripts:
  analyze:
    exec: dart analyze .
    description: Analyze a specific package in this project.

  check-format:
    exec: dart format --set-exit-if-changed .
    description: Check the format of a specific package in this project.

  format:
    exec: dart format .
    description: Format a specific package in this project.

  version:
    description: Updates version numbers in all build files
    run: bash scripts/version.sh

  test:
    run: dart test test/*
    description: Run all Dart & Flutter tests in this project.


  
