// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.64.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';

abstract class Massa {
  Future<int> sum({required int a, required int b, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSumConstMeta;

  Future<int> sub({required int a, required int b, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSubConstMeta;
}

class MassaImpl implements Massa {
  final MassaPlatform _platform;
  factory MassaImpl(ExternalLibrary dylib) =>
      MassaImpl.raw(MassaPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory MassaImpl.wasm(FutureOr<WasmModule> module) =>
      MassaImpl(module as ExternalLibrary);
  MassaImpl.raw(this._platform);
  Future<int> sum({required int a, required int b, dynamic hint}) {
    var arg0 = api2wire_i32(a);
    var arg1 = api2wire_i32(b);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_sum(port_, arg0, arg1),
      parseSuccessData: _wire2api_i32,
      constMeta: kSumConstMeta,
      argValues: [a, b],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSumConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "sum",
        argNames: ["a", "b"],
      );

  Future<int> sub({required int a, required int b, dynamic hint}) {
    var arg0 = api2wire_i32(a);
    var arg1 = api2wire_i32(b);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_sub(port_, arg0, arg1),
      parseSuccessData: _wire2api_i32,
      constMeta: kSubConstMeta,
      argValues: [a, b],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSubConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "sub",
        argNames: ["a", "b"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  int _wire2api_i32(dynamic raw) {
    return raw as int;
  }
}

// Section: api2wire

@protected
int api2wire_i32(int raw) {
  return raw;
}
// Section: finalizer
