// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.64.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';

class MassaPlatform extends FlutterRustBridgeBase<MassaWire>
    with FlutterRustBridgeSetupMixin {
  MassaPlatform(FutureOr<WasmModule> dylib) : super(MassaWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

// Section: finalizer
}

// Section: WASM wire module

@JS('wasm_bindgen')
external MassaWasmModule get wasmModule;

@JS()
@anonymous
class MassaWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external MassaWasmModule bind(dynamic thisArg, String moduleName);
  external dynamic /* void */ wire_sum(NativePortType port_, int a, int b);

  external dynamic /* void */ wire_sub(NativePortType port_, int a, int b);
}

// Section: WASM wire connector

class MassaWire extends FlutterRustBridgeWasmWireBase<MassaWasmModule> {
  MassaWire(FutureOr<WasmModule> module)
      : super(WasmModule.cast<MassaWasmModule>(module));

  void wire_sum(NativePortType port_, int a, int b) =>
      wasmModule.wire_sum(port_, a, b);

  void wire_sub(NativePortType port_, int a, int b) =>
      wasmModule.wire_sub(port_, a, b);
}
